### ISSUE TITLE
Milestones for the 3rd Review Meeting

### ISSUE THREAD

**Issue by yuichkun** [dawlet-team/dawlet-poc#7]
# Deadline

2020/02/16

#  TODOs

- [ ] Core
  - [ ] Enable Using IPC
- [ ] Launcher
  - [ ] Add Launching Utils
- [ ] Algolet
  - [ ] Setup Monaco Editor
  - [ ] Add Simple API
- [ ] Midilet
  - [ ] Enable Preview
